### PR TITLE
Auto-install requirements.txt if one exists

### PR DESCRIPTION
**Pull request by itamarst**
Also re-arrange slightly so changes to startup scripts don't require rebuilding the whole image.

### CODE REVIEW

**Comment by lukemarsden** [comment]
cool. What's the UX here then? Drop a requirements.txt file into your project, and restart Jupyter to auto install stuff? What happens if it goes wrong, does the user get to see the log?

**Comment by lukemarsden** [comment]
please check the UX for debugging this, document how it works, document how to interactively test it, then this LGTM

**Comment by itamarst** [comment]
Will do

**Comment by itamarst** [comment]
Will do, thanks

**Comment by itamarst** [comment]
So the current behavior is... not ideal:

1. The error is interleaved with the logs, so it is actually visible, but only if you know what you're looking for. So probably should be more visible.
2. Once the installation error happens, Jupyter fails to start.
3. At that point... you're stuck.

Failing to start if install fails isn't ideal. I could easily change it to continue if installation fails, but then the error won't be visible since it will almost immediately get hidden by the Jupyter UI starting up.

There's also the issue that if you break the installation badly enough Jupyter won't start at all.

So this suggests:

1. Maybe requirements.txt should result in new virtualenv with new kernel? So it should up as "user kernel" in the JupyterLab UI. That way Jupyter overall won't ever break.
2. A virtualenv would also prevent having to reinstall on every startup.
2. Figure out some way to pop-up errors in JupyterLab for visibility.

**Comment by itamarst** [comment]
I think as a first pass I'll try just putting errors in file, if that doesn't seem usable then we can add on notifications with e.g. https://github.com/fcollonval/jupyterlab_toastify

**Comment by itamarst** [comment]
OK, it's a lot better now, it adds a custom kernel and doesn't break startup if installation fails. Errors go to a text file in the root.

**Comment by itamarst** [comment]
OK, it's a lot better now, it adds a custom kernel and doesn't break startup if installation fails. Errors go to a text file in the root.

**Comment by itamarst** [comment]
OK, it's a lot better now, it adds a custom kernel and doesn't break startup if installation fails. Errors go to a text file in the root.

**Comment by itamarst** [comment]
OK, error case is now handled, and there is documentation, and it's a lot safer since it doesn't touch the main Jupyter install at all.

Docs: https://github.com/dotmesh-io/dotscience-docs/pull/50

**Comment by prisamuel** [comment]
Nice, also in the new UI - the logs aren't seen at all by default. I think most users won't see the startup logs now.

**Pull request merged**
